latitude = 34.7;
longitude = -86.6;
hour = 14;  % EST Time 24HR Clock, Integer [0,23]

% API Pull
latitude = chop(latitude, 6);
longitude = chop(longitude,6);

% Pulls atmospheric data for today
% Old API Call (no wind)   %atmosphericAPIurl = sprintf('https://api.open-meteo.com/v1/forecast?latitude=%g&longitude=%g&hourly=temperature_1000hPa,temperature_975hPa,temperature_950hPa,temperature_925hPa,temperature_900hPa,temperature_875hPa,temperature_850hPa,temperature_825hPa,temperature_800hPa,temperature_775hPa,temperature_750hPa,temperature_725hPa,temperature_700hPa,temperature_675hPa,temperature_650hPa,geopotential_height_1000hPa,geopotential_height_975hPa,geopotential_height_950hPa,geopotential_height_925hPa,geopotential_height_900hPa,geopotential_height_875hPa,geopotential_height_850hPa,geopotential_height_825hPa,geopotential_height_800hPa,geopotential_height_775hPa,geopotential_height_750hPa,geopotential_height_725hPa,geopotential_height_700hPa,geopotential_height_675hPa,geopotential_height_650hPa&wind_speed_unit=ms&forecast_days=1&models=gfs_seamless', latitude, longitude);
atmospheric_api_url = sprintf('https://api.open-meteo.com/v1/forecast?latitude=%g&longitude=%g&hourly=temperature_1000hPa,temperature_950hPa,temperature_975hPa,temperature_925hPa,temperature_900hPa,temperature_875hPa,temperature_850hPa,temperature_825hPa,temperature_800hPa,temperature_775hPa,temperature_750hPa,temperature_725hPa,temperature_700hPa,temperature_675hPa,temperature_650hPa,geopotential_height_1000hPa,geopotential_height_975hPa,geopotential_height_950hPa,geopotential_height_925hPa,geopotential_height_900hPa,geopotential_height_875hPa,geopotential_height_850hPa,geopotential_height_825hPa,geopotential_height_800hPa,geopotential_height_775hPa,geopotential_height_750hPa,geopotential_height_725hPa,geopotential_height_700hPa,geopotential_height_675hPa,geopotential_height_650hPa,wind_speed_975hPa,wind_speed_1000hPa,wind_speed_950hPa,wind_speed_925hPa,wind_speed_900hPa,wind_speed_875hPa,wind_speed_850hPa,wind_speed_825hPa,wind_speed_800hPa,wind_speed_775hPa,wind_speed_750hPa,wind_speed_725hPa,wind_speed_675hPa,wind_speed_650hPa,wind_speed_700hPa,wind_direction_1000hPa,wind_direction_975hPa,wind_direction_950hPa,wind_direction_925hPa,wind_direction_900hPa,wind_direction_875hPa,wind_direction_850hPa,wind_direction_825hPa,wind_direction_800hPa,wind_direction_775hPa,wind_direction_750hPa,wind_direction_725hPa,wind_direction_700hPa,wind_direction_675hPa,wind_direction_650hPa,vertical_velocity_1000hPa,vertical_velocity_975hPa,vertical_velocity_950hPa,vertical_velocity_925hPa,vertical_velocity_900hPa,vertical_velocity_875hPa,vertical_velocity_850hPa,vertical_velocity_825hPa,vertical_velocity_800hPa,vertical_velocity_775hPa,vertical_velocity_750hPa,vertical_velocity_725hPa,vertical_velocity_700hPa,vertical_velocity_675hPa,vertical_velocity_650hPa&models=gfs_seamless&timezone=America%%2FNew_York&forecast_days=1&wind_speed_unit=ms', latitude, longitude);
data = webread(atmospheric_api_url);

% Pulls elevation at coordinates
elevation_api_url = sprintf('https://api.open-elevation.com/api/v1/lookup?locations=%g,%g', latitude, longitude);
sealeveldata = webread(elevation_api_url);
atmosphericData.elevation = sealeveldata.results.elevation;

atmosphericData.pressures = 100*(1000:-25:650)';

atmosphericData.heights = [data.hourly.geopotential_height_1000hPa(hour + 1)...
    data.hourly.geopotential_height_975hPa(hour + 1)...
    data.hourly.geopotential_height_950hPa(hour + 1)...
    data.hourly.geopotential_height_925hPa(hour + 1)...
    data.hourly.geopotential_height_900hPa(hour + 1)...
    data.hourly.geopotential_height_875hPa(hour + 1)...
    data.hourly.geopotential_height_850hPa(hour + 1)...
    data.hourly.geopotential_height_825hPa(hour + 1)...
    data.hourly.geopotential_height_800hPa(hour + 1)...
    data.hourly.geopotential_height_775hPa(hour + 1)...
    data.hourly.geopotential_height_750hPa(hour + 1)...
    data.hourly.geopotential_height_725hPa(hour + 1)...
    data.hourly.geopotential_height_700hPa(hour + 1)...
    data.hourly.geopotential_height_675hPa(hour + 1)...
    data.hourly.geopotential_height_650hPa(hour + 1)]';

atmosphericData.temperatures = [data.hourly.temperature_1000hPa(hour + 1)...
    data.hourly.temperature_975hPa(hour + 1)...
    data.hourly.temperature_950hPa(hour + 1)...
    data.hourly.temperature_925hPa(hour + 1)...
    data.hourly.temperature_900hPa(hour + 1)...
    data.hourly.temperature_875hPa(hour + 1)...
    data.hourly.temperature_850hPa(hour + 1)...
    data.hourly.temperature_825hPa(hour + 1)...
    data.hourly.temperature_800hPa(hour + 1)...
    data.hourly.temperature_775hPa(hour + 1)...
    data.hourly.temperature_750hPa(hour + 1)...
    data.hourly.temperature_725hPa(hour + 1)...
    data.hourly.temperature_700hPa(hour + 1)...
    data.hourly.temperature_675hPa(hour + 1)...
    data.hourly.temperature_650hPa(hour + 1)]';

atmosphericData.vertical_velocities = [data.hourly.vertical_velocity_1000hPa(hour + 1)...
    data.hourly.vertical_velocity_975hPa(hour + 1)...
    data.hourly.vertical_velocity_950hPa(hour + 1)...
    data.hourly.vertical_velocity_925hPa(hour + 1)...
    data.hourly.vertical_velocity_900hPa(hour + 1)...
    data.hourly.vertical_velocity_875hPa(hour + 1)...
    data.hourly.vertical_velocity_850hPa(hour + 1)...
    data.hourly.vertical_velocity_825hPa(hour + 1)...
    data.hourly.vertical_velocity_800hPa(hour + 1)...
    data.hourly.vertical_velocity_775hPa(hour + 1)...
    data.hourly.vertical_velocity_750hPa(hour + 1)...
    data.hourly.vertical_velocity_725hPa(hour + 1)...
    data.hourly.vertical_velocity_700hPa(hour + 1)...
    data.hourly.vertical_velocity_675hPa(hour + 1)...
    data.hourly.vertical_velocity_650hPa(hour + 1)]';

atmosphericData.wind_directions = pi/180*[data.hourly.wind_direction_1000hPa(hour + 1)...
    data.hourly.wind_direction_975hPa(hour + 1)...
    data.hourly.wind_direction_950hPa(hour + 1)...
    data.hourly.wind_direction_925hPa(hour + 1)...
    data.hourly.wind_direction_900hPa(hour + 1)...
    data.hourly.wind_direction_875hPa(hour + 1)...
    data.hourly.wind_direction_850hPa(hour + 1)...
    data.hourly.wind_direction_825hPa(hour + 1)...
    data.hourly.wind_direction_800hPa(hour + 1)...
    data.hourly.wind_direction_775hPa(hour + 1)...
    data.hourly.wind_direction_750hPa(hour + 1)...
    data.hourly.wind_direction_725hPa(hour + 1)...
    data.hourly.wind_direction_700hPa(hour + 1)...
    data.hourly.wind_direction_675hPa(hour + 1)...
    data.hourly.wind_direction_650hPa(hour + 1)]';

atmosphericData.wind_speeds = [data.hourly.wind_speed_1000hPa(hour + 1)...
    data.hourly.wind_speed_975hPa(hour + 1)...
    data.hourly.wind_speed_950hPa(hour + 1)...
    data.hourly.wind_speed_925hPa(hour + 1)...
    data.hourly.wind_speed_900hPa(hour + 1)...
    data.hourly.wind_speed_875hPa(hour + 1)...
    data.hourly.wind_speed_850hPa(hour + 1)...
    data.hourly.wind_speed_825hPa(hour + 1)...
    data.hourly.wind_speed_800hPa(hour + 1)...
    data.hourly.wind_speed_775hPa(hour + 1)...
    data.hourly.wind_speed_750hPa(hour + 1)...
    data.hourly.wind_speed_725hPa(hour + 1)...
    data.hourly.wind_speed_700hPa(hour + 1)...
    data.hourly.wind_speed_675hPa(hour + 1)...
    data.hourly.wind_speed_650hPa(hour + 1)]';

atm = atmosphericData;